### ISSUE TITLE
Issue with main file brainlife version of this template

### ISSUE THREAD

**Issue by DanNBullock** [francopestilli/app-template-matlab#1]
https://github.com/francopestilli/app-template-matlab/blob/4fdfde3173bc6245e71b469cc0bbaf76eee5ec90/main#L13

I couldn't make an issue in the brainlife version of this, so I'm making this issue here (which is why it won't make sense).

The main.m that is on brainlife is a python template, and doesn't actually reflect the need to compile the matlab code, which I should think is pretty standard of matlab main files.

**Comment by DanNBullock** [comment]
An example of the compiled.sh file can be found here:  https://github.com/brainlife/app-wmaSeg/blob/3.8/compile.sh

**Comment by filipinascimento** [comment]
Hi, I've created a template ( https://github.com/filipinascimento/bl-network-template-matlab ) with working compilation and submodules code. I can adapt this to be more generic and replicate the functionality of this template.

**Comment by DanNBullock** [comment]
Hi @filipinascimento, I think this is a great template, but it may be better to push this to the brainlife branch of this template (https://github.com/brainlife/app-template-matlab).  This issue was created here on @francopestilli's branch because the branch had issue creation locked at the time.

**Comment by francopestilli** [comment]
@filipinascimento I think it would be perfectly fine to fork this tutorial as an App Toturla for the Network Neuroscience folks. I will fork it into github/brainlife

please push updates there.

**Comment by francopestilli** [comment]
@DanNBullock I need more information to be able to act on your pull request

**Comment by francopestilli** [comment]
Perhaps you got confused by the loops in forks? 
This is the simple app template on brainlife https://github.com/brainlife/app-template-matlab

**Comment by DanNBullock** [comment]
Hi Franco,

I made the issue here, on this repo, because the brainlife branch had issues disabled.  @soichih enabled issues Saturday, which is why this seems confusing now.  I believe that future issues and such can now be addressed there, directly on the brainlife branch, so I'm going to go ahead and close this comment.
